### ISSUE TITLE
RTBF Auvio

### ISSUE THREAD

**Issue by eenbroleke** [Catch-up-TV-and-More/xmltv#1]
Hi, thanks for the good work !
It seems that the script will not handle the RTBF auvio channels properly : they are not displayed in the TV guide nor in the TV channel list.

Tested with both the tvguidebe and the tvguideall.

**Comment by wwark** [comment]
Hi @eenbroleke,
Yes you are right.
RTBF auvio doesn't provide Live TV (all day) but live tv available just for one program at a precise time.
So we don't propose them throw the kodi mode TV so not activated in the xmltv.
These live tv are just available directly in the plugin with all informations related to the program.

Thanks,
Wwark.

**Comment by eenbroleke** [comment]
Hi, thanks for your feedback.
Is there a way to recreate the all_day live tv based on the different information available ?
Or do you mean that there is no such thing as a view available for the whole day at any given time ? If not, could there still be a partial view that make sense around the time of refresh ?
I'm just wild guessing, as I'm very much interested in getting something as user friendly as possible for those channels.

**Comment by wwark** [comment]
Hi,
I think it will be very difficult and just for 4 hours of live per day for each channel.
Maybe one day, RTBF will propose live all day long.

Thanks,
Wwark
