### ISSUE TITLE
Guide Belgique vide pour certaines chains

### ISSUE THREAD

**Issue by alexbelgium** [Catch-up-TV-and-More/xmltv#14]
Hello, 

Thanks for this great tool! Here is a copy paste of a post initially on the main catch up issue log :

The TV guide does not have data for some key channels (sur as Een, la une, la deux, la trois, rtl-tvi, rtl-club). However, there is data for other Belgium channels (such as ketnet) and for French ones (like m6)

Checking the tv_guide_be.xml file (ex : https://raw.githubusercontent.com/Catch-up-TV-and-More/xmltv/master/tv_guide_be_20220102.xml) , I can see there is no data for those specific channels, although there is for other channels.

Thanks!

**Comment by alexbelgium** [comment]
Looks like telerama stopped providing xml for Belgian channels

**Comment by Fabianvk** [comment]
Bonjour,
D'après plusieurs commentaires de l'équipe Télérama sur l'application Android il s'agirait d'un bug.
13/1/2022 : "_[...] Nous avons bien identifié ce problème technique et travaillons activement avec notre partenaire pour rétablir les flux sur les chaînes manquantes belges [...]_".

**Comment by Fabianvk** [comment]
Le problème semble être résolu chez moi depuis aujourd'hui.

**Comment by alexbelgium** [comment]
Merci, bonne nouvelle, je ferme l'issue alors. Bonne journée
