### ISSUE TITLE
Guide Canada

### ISSUE THREAD

**Issue by JungleJim42** [Catch-up-TV-and-More/xmltv#15]
Bonjour!

J'aimerais beaucoup avoir un guide EPG pour les chaines canadiennes. L'information n'est pas disponible gratuitement, mais il est possible d'avoir un abonnement payant à Schedulesdirect.org qui peut fournir l'information pour le guide. Il est possible d'extraire l'information de schedules direct avec xmltv, mais je ne sais pas comment intégrer cette information dans CatchupTV. Je comprends qu'il ne serait pas possible d'héberger ce guide (payant) sur le serveur de CatchupTV comme pour les autres guides, mais j'aimerais pouvoir générer le fichier localement et que CatchupTV utilise ma version locale pour le guide télé.  Je pourrais moi-même fabriquer un fichier "tv_guide_ca_20220101.xml" formaté comme les autres pays. Est-ce que c'est possible de faire intégrer mon fichier par CatchupTV?

Voici un extrait du fichier généré automatiquement par xmltv à partir de schedulesdirect. Je comprends que je devrai faire un reformattage.

[xmltv_schedulesdirect.txt](https://github.com/Catch-up-TV-and-More/xmltv/files/7892518/xmltv_schedulesdirect.txt)

**Comment by JungleJim42** [comment]
J'ai plusieurs éléments mais je ne sais pas comment intégrer le tout dans le plugin. Je pourrais fournir les fichiers à la demande. 
- tv_grab_na_dd peut aller chercher les infos sur Schedulesdirect (mais il faut un mot de passe) (ce n'est pas moi qui ai fait le programme). J'ai aussi le fichier de .conf avec les bonnes chaînes correspondant à Catchup.
- j'ai refait le skeleton "ca_live.py" en ajoutant les bons "xmltv-id" correspondants à Schedulesdirect pour les chaines supportées par Catchup
- j'ai aussi les ajouts pour "ca" dans le fichier "channels.py"
- je peux ainsi obtenir (manuellement) un fichier avec chaines et programmes qui ressemble au format tv_guide_ca.xml. Par contre il y a un peu de ménage à faire pour formatter le contenu exactement commes les autres (par exemple changer le code de ISO-8859-1 à UTF-8).
Est-ce qu'il est possible de partir de ceci pour quelqu'un qui maitrise mieux le plugin que moi? Merci!

**Comment by sy6sy2** [comment]
Hello !
Concernant l'utilisation de ton fichier XML cela va dépendre de si tu utilises IPTV Manager ou non.
Si tu ne l'utilises pas et que tu utilises s'implement la catégorie "Live TV" de CUTV&M alors tu dois pouvoir mettre en place dans ton dossier user data le fichier XMLTV que CUTV&M attend ; mais je pense que ça demande quelques modifs au niveau du code du plugin... 😕

**Comment by JungleJim42** [comment]
Est-ce que ce serait possible de changer le fichier "ca_live.py" du plugin officiel pour ma version? C'est le même fichier, sauf que j'ai ajouté les tags "xmltv-id" pour les différents canaux. Je crois que ça ne changera rien pour la majorité des gens, mais ça permettra de faire la bonne association pour ceux qui utilisent Schedulesdirect. Quand je change localement chez moi, ça permet à iptv manager de générer une playlist avec les bons canaux et les xmltv-id corrects.

[ca_live.py.txt](https://github.com/Catch-up-TV-and-More/xmltv/files/7909384/ca_live.py.txt)

Aussi, dans un monde idéal, j'aimerais pouvoir ajouter le grabber "tv_grab_na_dd" dans l'automatisation de la recherche de guides. Par contre, plutôt que d'aller chercher une version du guide sur le web, il pourrait générer un fichier "tv_guide_ca_date.xml" localement. Cette option ne serait activée que chez ceux qui ont un nom d'usager et un mot de passe de schedulesdirect dans le fichier "tv_grab_na_dd.conf". Je pourrais essayer de bidouiller le code, mais il faudrait m'indiquer quels fichiers sont à modifier, je ne saisis pas complètement la chaine de comment les éléments du plugin interagissent pour que le guide se retrouve dans iptvmanager.

.

**Comment by sy6sy2** [comment]
Merci pour ton fichier, je viens de push la version `0.2.37~beta09` du plugin avec tes changements. En espérant que ça fonctionne pour toi !

Pourquoi pas pour le grabber ; est-ce qu'il est écrit en Python ? Tu as un lien GitHub de celui afin qu'on voit pour l'intégrer a plugin ? Merci

**Comment by JungleJim42** [comment]
Merci pour le fichier ca.py! 

Ce serait vraiment génial d'intégrer le grabber dans CatchupTV mais je ne sais pas dans quelle mesure ce serait compliqué.

tv_grab_na_dd
Le github est : https://github.com/XMLTV/xmltv/tree/master/grab/na_dd 
Mais il est en perl.

Une autre solution possible: auparavant j'utilisait un plugin de kodi qui se nomme SchedulesDirect to xmltv:
Le github est : https://github.com/primaeval/script.schedules.direct
Il est en python. Il fonctionnait parfaitement avec kodi 18 mais ne fonctionne plus sous kodi 19 matrix. Je ne sais pas pourquoi.

Dans les deux cas il y a l'enjeu qu'il faut un code d'usager et un mot de passe pour accéder aux infos de schedulesdirect. Cela pourrait être une option de plus de Catchup, comme l'abonnement à certaines chaînes. Par contre, ce serait problématique de générer un fichier xml sur un serveur public comme pour les autres grabbers, il faudrait probablement générer le xml localement pour chaque usager.

**Comment by JungleJim42** [comment]
J'ai trouvé un autre grabber de la "famille" XMLTV qui est compatible avec Schedulesdirect: 
tv_grab_zz_sdjson
Le github est: https://github.com/XMLTV/xmltv/tree/master/grab/zz_sdjson
Je ne sais pas si ce serait plus facile avec celui-ci que tv_grab_na_dd. Je crois que le plugin mentionné plus haut (SchedulesDirect to xmltv) utilise tv_grab_zz_sdjson.

**Comment by JungleJim42** [comment]
J'ai fait un test local, et je confirme que tv_grab_zz_sdjson s'intègre très bien dans le fichier update_all_tv_guides.py! J'ai fait deux modifications:
1) dans update_all_tv_guides.py, j'ai copié le code pour tv_grab_it en l'adaptant (au début dans la liste des tv_grab)
2) dans channels.py, j'ai ajouté la liste des chaînes "ca".
Avec ces deux modifications, exécuter (localement) update_all_tv_guides.sh permet de générer les fichiers tv_guide_ca_DATE.xml et de les fusionner correctement. Il sont utilisables dans Kodi sans autre modification.
Par contre, même si ça fonctionne localement, puisque les informations de SchedulesDirect nécessitent un abonnement payant, il ne serait pas possible d'héberger les guides xml sur le serveur comme pour les autres pays. Il faudrait donc modifier un peu le plugin, pour qu'au moment de la mise-à-jour du guide, que pour les canaux "ca", au lieu de télécharger les fichiers xml, qu'il les génère localement avec tv_grab_zz_sdjson (selon le même code utilisé dans update_all_tv_guides.py). Et aussi ajouter un paramètre supplémentaire où l'usager pourrait inscrire son code d'accès et mot de passe de schedules direct.

[code_a_ajouter_dans_channels.py.txt](https://github.com/Catch-up-TV-and-More/xmltv/files/7918754/code_a_ajouter_dans_channels.py.txt)
[code_a_ajouter_dans_update_all_tv_guides.py.txt](https://github.com/Catch-up-TV-and-More/xmltv/files/7918755/code_a_ajouter_dans_update_all_tv_guides.py.txt)

**Comment by JungleJim42** [comment]
Je continue mes recherches. 

- J'ai refait le fichier ca_live.py en ajoutant cette fois les xml-id de TOUTES les chaînes de la section "ca", y compris les différentes villes pour ici-télé et CBC. J'ai aussi changé le format pour "json.schedulesdirect.org", qui est plus récent. Je crois que l'on peut inclure ce fichier directement au plugin sans incidence, il n'y a que les xmltv-id d'ajoutées. J'ai testé et cela permet à IPTV Manager de générer la playlist.m3u8 avec les bons tags.

[ca_live.py.txt](https://github.com/Catch-up-TV-and-More/xmltv/files/7935438/ca_live.py.txt)

- J'ai testé le module "tv_grab_zz_sdjson" localement et il génère les guides pour le Canada dans un format compatible avec Catchup, IPTV Simple et IPTV Manager sans manipulation différente que les autres tv_grab utilisés par Catchup (comme tv_grab_it, par exemple). Si je me fais une version locale de xmltv et que je modifie "update_all_tv_guides.py" pour ajouter "tv_grab_zz_sdjson", il génère correctement les fichiers sous forme "tv_guide_ca_20220125.xml" pour les chaînes "ca". 

[ajout pour update_all_tv_guides.py.txt](https://github.com/Catch-up-TV-and-More/xmltv/files/7935444/ajout.pour.update_all_tv_guides.py.txt)

- J'inclus aussi le fichier de configuration de "tv_grab_zz_sdjson" avec seulement les chaines de CatchupTV sélectionnées, pour économiser les ressources. ATTENTION, je n'ai pas inclus mon username et password dans ce fichier, et donc tv_grab_sdjson ne fonctionnera pas. Il faut un abonnement à schedulesdirect pour le faire fonctionner.

[tv_grab_zz_sdjson (sans mot de passe).conf.txt](https://github.com/Catch-up-TV-and-More/xmltv/files/7935445/tv_grab_zz_sdjson.sans.mot.de.passe.conf.txt)

- J'ai aussi ajouté les xml-id de TOUTES les chaînes de la section "ca" dans le fichier "channels.py" qui est utilisé par xmltv pour générer les guides. Cela est nécessaire pour que update_all_tv_guides génère correctement les guides. 

[channels.py.txt](https://github.com/Catch-up-TV-and-More/xmltv/files/7935450/channels.py.txt)

- Ce qu'il faudrait faire selon ma compréhension:

a) ajouter un endroit dans Catchup pour entrer le username et password de Schedulesdirect

b) que cet username et password soient copiés dans le fichier tv_grab_zz_sdjson.conf

c) lorsque Catchup procède à la mise-à-jour du guide, plutôt que de chercher à télécharger les guides sur le serveur sous forme de "tv_guide_it_20220125.xml", pour le Canada, qu'il génère localement le guide en activant "tv_grab_zz_sdjson".  Comme précisé plus haut, ce module fonctionne exactement comme "tv_grab_it" ou les autres et génère un guide compatible.

J'atteints les limites de mes compétences, dites-moi si je pourrais faire autre chose pour aider à la réalisation de l'ajout des guides pour les chaînes "ca". Merci!

**Comment by JungleJim42** [comment]
Autre sujet: je propose que "Ici-RDI" soit classé dans le paquet "ca" plutôt que le paquet "wo". Cela permettrait d'avoir accès au programmes pour cette chaine étant avec Schedulesdirect comme les autres chaînes de la famille "ca". Je ne sais pas où seraient tous les endroits où il faudrait effectuer une modification par contre:
- déplacer icirdi.py de /ressources/lib/channels/wo vers /ressources/lib/channels/ca, 
- modifier dans /ressources/lib/skeletons: ca_live.py et wo_live.py, 
- dans xmltv le fichier "channels.py", 
- peut-être d'autres?

**Comment by JungleJim42** [comment]
Bonjour! Je continue mon idée d'intégrer les guides pour les chaines "CA" dans Catchuptv. J'ai créé des ajouts au plugin CatchupTV qui permettent de le faire. C'est imparfait parce que je ne saisis pas complètement l'intégration entre les scripts, mais tous les éléments sont présents et ça fonctionne localement. 

Il suffit de télécharger le .zip et de l'installer par-dessus le plugin de catchup (il y a de nouveaux fichiers pour tv_guide_ca et deux fichiers du plugin original sont modifiés - un pour la liste de chaines, et un pour activer le reste). Il y a des instructions précises (fichier instructions.txt) et toutes les modifications sont indiquées dans les fichiers. 

Il reste que cet ajout ne fonctionne qu'avec un username et password de Schedules direct. Il est possible d'avoir un accès gratuit pour 7 jours pour fins de tests.

[tv_guide_ca.zip](https://github.com/Catch-up-TV-and-More/xmltv/files/8053922/tv_guide_ca.zip)

**Comment by JungleJim42** [comment]
Bonjour! Je continue mon idée d'intégrer les guides pour les chaines "CA" dans Catchuptv. J'ai créé des ajouts au plugin CatchupTV qui permettent de le faire. C'est imparfait parce que je ne saisis pas complètement l'intégration entre les scripts, mais tous les éléments sont présents et ça fonctionne localement. 

Il suffit de télécharger le .zip et de l'installer par-dessus le plugin de catchup (il y a de nouveaux fichiers pour tv_guide_ca et deux fichiers du plugin original sont modifiés - un pour la liste de chaines, et un pour activer le reste). Il y a des instructions précises (fichier instructions.txt) et toutes les modifications sont indiquées dans les fichiers. 

Il reste que cet ajout ne fonctionne qu'avec un username et password de Schedules direct. Il est possible d'avoir un accès gratuit pour 7 jours pour fins de tests.

[tv_guide_ca.zip](https://github.com/Catch-up-TV-and-More/xmltv/files/8053922/tv_guide_ca.zip)

**Comment by JungleJim42** [comment]
Bonjour! En attendant d'avoir une solution plus complète, est-ce que ce serait possible d'intégrer seulement le fichier ca_live.py suivant à la version courante. Le seul changement par rapport à l'original est que j'ai ajouté le tag "xmltv_id" pour TOUTES les chaînes CA (incluant les choix de villes), afin que cela fonctionne pour le guide. 
[ca_live.zip](https://github.com/Catch-up-TV-and-More/xmltv/files/8238614/ca_live.zip)
Merci!

**Comment by sy6sy2** [comment]
Hello @JungleJim42,
Désolé je n'ai pas encore eu le temps de regarder pour intégrer le support de Schedulesdirect mais j'y pense toujours 😉 .

Pas de problème pour les xmltv_id ; je vais faire ça !
