### ISSUE TITLE
Invalid episode-num blocks EPG loading for UK xml

### ISSUE THREAD

**Issue by mchubby** [Catch-up-TV-and-More/xmltv#16]
Source:
https://raw.githubusercontent.com/Catch-up-TV-and-More/xmltv/81606df/tv_guide_uk_20220314.xml

programme{'start': '20220314000000', 'channel': '1014.tvguide.co.uk', 'title': [('Forensic Detectives', 'en')], 'stop': '20220314010000', 'sub-title': [('Out of the Grave', 'en')], 'desc': [('How splinters of bone helped forensic investigators to trace a murderer four years after the victim first disappeared.', 'en')], 'category': [('News', 'en'), ('Current Affairs', 'en')], 'episode-num': [('2.6/10.', 'xmltv_ns')], 'subtitles': [{'type': 'teletext'}], 'star-rating': [{'value': '7.8/10'}]}

yields this kodi.log error:

ERROR <general>: [Catch-up-TV-&-More] xmltv module failed with error: invalid literal for int() with base 10: '6/10'

**Comment by sy6sy2** [comment]
Hi, thank you for this issue!
Can you try 0.2.38~beta03 version of the add-on?
I tried an hot-fix to ignore episode number if format is "wrong".
Thank you!

**Comment by mchubby** [comment]
Yup, it works well this way.
Thanks!

**Comment by kevwag** [comment]
> Source: https://raw.githubusercontent.com/Catch-up-TV-and-More/xmltv/81606df/tv_guide_uk_20220314.xml
> 
> programme{'start': '20220314000000', 'channel': '1014.tvguide.co.uk', 'title': [('Forensic Detectives', 'en')], 'stop': '20220314010000', 'sub-title': [('Out of the Grave', 'en')], 'desc': [('How splinters of bone helped forensic investigators to trace a murderer four years after the victim first disappeared.', 'en')], 'category': [('News', 'en'), ('Current Affairs', 'en')], 'episode-num': [('2.6/10.', 'xmltv_ns')], 'subtitles': [{'type': 'teletext'}], 'star-rating': [{'value': '7.8/10'}]}

@mchubby I'm confused: 

1014.tvguide.co.uk maps to **Quest Red** channel, which isn't even available in Catch-up-TV-and-More!
If you look at the top part of the xml in that file, **Dave** IS listed as <channel id="432.tvguide.co.uk">, it IS available in the add-on but there's no <programme channel="432.tvguide.co.uk" start="xxxxxx" stop="xxxxxx"> data for that channel.
Other channels, such as **Yesterday**(320.tvguide.co.uk),  **Drama** (871.tvguide.co.uk) and **Blaze** (1013.tvguide.co.uk) don't appear ANYWHERE in the XML, either in a <channel id ...> or a <programme channel ...> tag.

I'm still learning all this GitHub stuff so maybe I'm missing something here but I'm struggling to understand how and why an issue gets opened about EPG data for a channel the plugin doesn't support, the issue then gets "fixed" and closed without anyone noticing that nearly all of the EPG data is missing for the channels that the plugin does support?? 

I've opened an issue (#17) about that problem (it looks like the daily scrape script times-out before tvguide.co.uk has time to respond), so hopefully someone will be able to fix the problem. I'm just puzzled as to why nobody else seems to have noticed that the entire EPG for the supported UK channels is empty but somehow you noticed a problem with a channel that isn't even there??

**Comment by mchubby** [comment]
Yes, I don't know why, but programme guide data for UK channel is scraped en masse by the script on a specific set of webpages.
As I understand, the result is exported to this very repository.

On the Kodi end, the xml files are downloaded and imported by the plugin, regardless of whether the channel is used or not.
A specific edge case caused the parsing to fail, hence why it was worked around by commenting some parts IIUC.
