### ISSUE TITLE
Two suggestions/requests for the xmltv files

### ISSUE THREAD

**Issue by bouscram** [Catch-up-TV-and-More/xmltv#2]
Hi! I'm more than happy to have found your repo which seems to be the only one currently available for French TV. I use it with EyeTV, so I use the raw Telerama files to get the right time.
I have 2 requests which would make me even happier:

1) Could you add the actors and directors tags to the xmltv file?
2) would it be possible to get a light variant with with only the DVB channels?

Thanks!

**Comment by SylvainCecchetto** [comment]
Hi,

Concerning actors and directors tags I think the the perl script needs to be improved. We are not the authors of this script. The original script come from this repo https://github.com/zubrick/tv_grab_fr_telerama, maybe you can ask for this feature directly here.

What do you mean by "only DVB channels"? Only TNT channels?

**Comment by bouscram** [comment]
Yes (I didn't want to use the French specific term ;-) )

**Comment by bouscram** [comment]
Sylvain, regarding the casting, I looked at the script Github, and I've seen they have added recently an option for it (--casting). Look at https://github.com/zubrick/tv_grab_fr_telerama/issues/24

**Comment by SylvainCecchetto** [comment]
I will add something in the Python file in order to generate a special XMLTV file with only TNT channels for you ;-)

Also, I will update the telerama script to test this new `--casting` option.

I will try to do this changes tonight, I will let you know here so that you can test.

**Comment by bouscram** [comment]
Thanks. I took my afternoon yesterday to make it work on my own (on macOS, which, combined with my complete absence of knowledge in Perl, brought some difficulties in installing the XMLTV framework). I succeeded, so I can tell it works fine (I also used the "--no_htmltags" option). Anyway I think it's a large improvement for all users, not just me...

**Comment by SylvainCecchetto** [comment]
I never managed to get xmltv-grabbers scripts to work on my mac, can you tell me what to do in outline please?

I will add `--no_htmltags` also ;-)

**Comment by SylvainCecchetto** [comment]
What do you think of the latest commits?
* I updated `tv_grab_fr_telerama` to be able to use `--casting` and `--no_htmltags`
* I added `--casting` and `--no_htmltags` in the bash script
* I modified the python script in order to generate TV guides for TNT FF

The script `update_all_tv_guides.sh` is currently running on my Linux server so you will see another commit later tonight with the changes concerning `--casting` and `--no_htmltags` options. Let me know later if all is correct for you ;-)
