### ISSUE TITLE
France 5 missing from TNT files

### ISSUE THREAD

**Issue by bouscram** [Catch-up-TV-and-More/xmltv#3]
Hello Sylvain.
I just noticed that France 5 is not (anymore ?) in the TNT listings. I checked it is in the full French files.

**Comment by SylvainCecchetto** [comment]
Hi,
Do you mean that France 5 is not in M3U files or in the "France" Catch-Up TV & more menu?

**Comment by bouscram** [comment]
In the XML files (https://github.com/Catch-up-TV-and-More/xmltv/blob/master/tv_guide_fr_tnt_local.xml and https://github.com/Catch-up-TV-and-More/xmltv/blob/master/tv_guide_fr_tnt.xml)

**Comment by SylvainCecchetto** [comment]
Sorry, I just realize that this issue is on the xmltv repo and not on the plugin.video.catchuptvandmore repo...

Strange, maybe a bug during the grab of the last night, I will check tomorrow to see if it's fixed.
thank you for the report!

**Comment by SylvainCecchetto** [comment]
Still no France 5 programmes in XMLTV files. Maybe the channel ID has changed on Telerama. I will check that today 😉

**Comment by SylvainCecchetto** [comment]
My fault, I forgot to add France 5 in the Python file....
Should be fixed now, thank you!
