### ISSUE TITLE
Links to XMLTV fr, be, uk... dead.

### ISSUE THREAD

**Issue by Tos26** [Catch-up-TV-and-More/xmltv#4]
Hello,

Since two days, the links given in the documentation on the live tv direct in Kodi is no longer active

    France : http://bit.ly/tvguidefr
    Belgique : http://bit.ly/tvguidebe
    Royaume-Uni: http://bit.ly/tvguideunitedkingdom

Is there a problem on Cron trigger?

**Comment by SylvainCecchetto** [comment]
I Tos26,

Yes I just noticed this issue this morning. I will try to fix this issue.

Thank you for this notification 😉

**Comment by SylvainCecchetto** [comment]
I updated the script with another method (I only grab 1 day each night instead of 7).
Everything should work in 2 or 3 days.

I keep this issue open until we are sure that everything works again

**Comment by briceparmentier** [comment]
Hi!
Thank you @Tos26 for reporting this, I was trying to setup this feature on my LibreElec instance, and I was getting nothing on the programs or on the TV channels informations.
Will we have to update manually the PVR plugin on KODI ?
Thanks for the quick fix !

**Comment by Tos26** [comment]
Thank you for your reactivity Sylvain, everything works now. I let you close the ticket when you're comfortable with the fixing solution

**Comment by briceparmentier** [comment]
Oh yeah it works also on my side ! Thanks a lot for the reactivity !

**Comment by SylvainCecchetto** [comment]
Perfect 😉
