### ISSUE TITLE
ImportError: No module named 'pytz'

### ISSUE THREAD

**Issue by lowflyerUK** [Catch-up-TV-and-More/xmltv#6]
Did something break a few days ago? It looks like no new data and "...ImportError: No module named 'pytz'..." in log.txt

**Comment by SylvainCecchetto** [comment]
Oh yes, something is wrong on my server. I will check that today. Thank you 😊

**Comment by SylvainCecchetto** [comment]
Should work now. Thank you for reporting this issue!

**Comment by lowflyerUK** [comment]
Hi!

Brilliant!! Thanks for fixing it so quickly. And thanks for your great
work. It is very much appreciated.

All the best, Andy

**Comment by SylvainCecchetto** [comment]
Thank you for your message 😄
Feel free to open an issue or a PR at any time if you need more channels/countries.

**Comment by lowflyerUK** [comment]
Hi! It looks as if this error is back.

**Comment by SylvainCecchetto** [comment]
Oups, I recently upgraded Python on my server and I forgot to reinstall this package. 
The next update should be good 😉
Thank you for the ping!

**Comment by lowflyerUK** [comment]
Hi Sylvain,

Did something else go wrong with the french data collection? There is no
data for 13th & 14th August.

Thanks!!

All the best, Andy

**Comment by sy6sy2** [comment]
Hi Andy,

The script seems to works, maybe a change on Telerama causes the grabber to fail?
I will check that tomorrow 😉 .

**Comment by sy6sy2** [comment]
It seems that is a on the Telerama website side.
If you check here https://television.telerama.fr/tele/grille?jour=+5 there is no program data from 12th August 😕 
We will wait to see if the fix the issue.

**Comment by lowflyerUK** [comment]
Ah yes, that would explain it! Hopefully it will come back!

**Comment by lowflyerUK** [comment]
Actually it looks quite interesting... it alternates, one full day and one
day with only a few hours.

**Comment by sy6sy2** [comment]
Ha ha this is strange 😁
I recently open an issue on the grabber repo just to notify grabber dev about this behaviour. 

Also, I recently modified my code. Normally my script should not produce the XMLTV file if there is no program for this day.

**Comment by lowflyerUK** [comment]
Hi! You have probably noticed that the data in most days of the French xml
files continues to be wrong. On the telegram website everything looks OK
for 5 (or maybe 6) days but not 7. Maybe it would be possible for you to do
a slightly different test in update_all_tv_guides.py at line 162. Instead of

            if os.path.exists(xmltv_fp):
                print('\t\t\t* This file already exists --> Nothing to do',
flush=True)
            else:
                cmd =.....

Maybe

            if os.path.exists(xmltv_fp):
                print('\t\t\t* This file already exists --> Now check for
size', flush=True)
                if os.path.getsize(xmltv_fp) > 300000:
                    print('\t\t\t* This file is big enough --> 'Nothing to
do', flush=True)
                else:
                    cmd =.....

With a more intelligent guess of the threshold filesize.

Just an idea. Thanks again for your wonderful work!

**Comment by sy6sy2** [comment]
Hi!

I did not check in the XMLTV files but if I understand correctly here is the problem:

* For offset 7 we have some TV shows but not all TV shows (some are missing)
* My script save the file with only some TV shows
* Next day, the script will no try to grab again telerama for day offset 6 because if we already have a file it assumes that we already have the correct TV guide. But this is wrong because we miss some TV shows.

Is it correct? If yes, maybe can I simply reduce the offset just to be sure that when we grab a day we don't miss anything?

Thank you very munch for your help!

**Comment by lowflyerUK** [comment]
Hi!

Yes, I think you are correct. If you get an xml file for offset 7, even if
it has very few TV shows, the script never replaces it, even if, when that
day is offset only 6 or 5..., all the TV shows are there.

I agree that taking offset 6 would help, but the best would be to test each
day to see how many shows are there, or maybe to test if there are shows
for every hour, and if not, to get the day again.

What do you think?

All the best, Andy

**Comment by lowflyerUK** [comment]
Hey you have been busy!

That worked :) Good idea to have a country specific raw_min_size. Let's
hope they don't change things so that raw_min_size will have to be changed.

Is there a good reason that ModuleNotFoundError: No module named 'pytz' has
come back in the log ?

Thanks for your great work

**Comment by sy6sy2** [comment]
Thank you for keeping an eye on this repo!

My fault, on the last run I started the command from another user without the pytz module. Another run is still in progress and should come soon.

I also need to take some time to fix UK and IT... 😕
