### ISSUE TITLE
Is it possible to update more often?

### ISSUE THREAD

**Issue by lowflyerUK** [Catch-up-TV-and-More/xmltv#7]
Hi! Thanks again for your great work!

I was annoyed the other day because of a programme change after I set up a recording. If I understand well, your system for french tnt captures the programmes for today+7. Then, so long as the xmltv file is big enough, this file stays the same even if the programme is changed on telerama.  

I can see that you don't want to download all programmes every day, and that it is not possible to only download changes, but maybe it would be possible to update all programmes for the following day as well as today+7 and for any days with too small files? That way any discrepancy between what I have set to record and the latest xmltv schedule will allow me to update my recording.

Thank you!!!

Best wishes, Lowflyer

**Comment by sy6sy2** [comment]
Hi!
Sorry I completely forget to answer :-/

I'm not sure to understand, do you mean that a programme list for one day can change on telerama? If yes, does it happen often?

**Comment by lowflyerUK** [comment]
Hi!

I haven't done a huge analysis, but in last few months I have set up maybe
50 recordings and maybe 2 or 3 have failed either because the timing
changed or because the program changed.

For my uk xmltv setup I collect the epg from tnt every day for the next 7
days. For any recordings that I have setup I test every day that the
program schedule hasn't changed. Most weeks I get a notification that
something has changed. So in the UK at least, schedules change most weeks.
Not sure if that is useful for FR.

Hope this helps!

All the best

**Comment by sy6sy2** [comment]
Ok I understand your issue.

If we are day D, I can force my script to re-download programmes of day D+1 each night. Do you thing it will fix your issue?

**Comment by lowflyerUK** [comment]
Hi !

Thanks! Yes, I think that would fix it ! Any change occurring for the
schedule of D+1 since it was originally captured (normally 6 days ago?)
would be updated. And the total traffic is 2/7ths of what it would have
been if you captured all the data every day.

Great stuff :)

**Comment by sy6sy2** [comment]
I pushed a commit. I hope it will fix your issue!
Thank you for your help!
I will close the issue but feel free to re-open/open another one 😉

**Comment by lowflyerUK** [comment]
Hi !

Something odd happened last night. I had a recording scheduled for tomorrow
(20/9/20). My system warned me that the schedule had changed. I thought
that your new procedure was working well ! However I see that the xml files
produced for tomorrow are very small and have only a few programmes - for
example tv_guide_fr_20200920.xml. Maybe telerama was doing an update at the
same time ?

I suggest we do nothing and see if it happens again.

Thanks !!

**Comment by lowflyerUK** [comment]
Hi again !

The same odd thing happened last night. tv_guide_fr_20200923.xml doesn't
have enough programmes. Maybe there is an underlying issue that prematurely
halts the capture some days. I had that problem once with characters that
were rejected by my Python xml modules.Although it's hard to see how that
could happen some days and not others for the same data ! Can you add a bit
more debugging info to your log files ?

Thanks !!

**Comment by sy6sy2** [comment]
Hi!

Ah shit 😕
Did you check the raw files to see if all programmes are in?

I will check the log.

**Comment by lowflyerUK** [comment]
Hi again !

Ah yes, tv_guide_fr_telerama_20200923.xml in raw is 1.69MBytes and has lots
of programmes but tv_guide_fr_20200923.xml in xmltv is only 89kBytes. That
can't be right.

All the best !

**Comment by lowflyerUK** [comment]
It looks as though all the programmes in tv_guide_fr_20200923.xml start
very late on 20200922 and continue into 20200923 or start very late on
20200923 ???

**Comment by sy6sy2** [comment]
Oh, maybe an error on my side concerning the "if" date check?
I will look at that! Thank you for the investigation!

**Comment by sy6sy2** [comment]
Hi, so, this is what I did:

* Now stdout and stderr outputs of each grabber run are redirect to `raw/xxxx_stdout.log` and  `raw/xxxx_stderr.log` files. So the main `log.txt` file is easier to read.
* I removed the specific TNT French guide files... With more time I will enable it again
* I added more verbose informations in the log file (number of programmes for each file)
* Now the script run at 12H on my server (French hour)

I hope everything will be good for you. If you notice some errors, as usual ping me 😉 
Thank you!

**Comment by lowflyerUK** [comment]
You are a REAL STAR !! I noticed all the logs and that the time has changed
when it gets called.

Let's keep our eye on it.

Thanks again!!

**Comment by lowflyerUK** [comment]
Hi Sylvain!

I hope that you are well.

It looks as though telerama.fr has broken. The last data is for Wednesday
morning 2/12/20. Hopefully they will get going again soon.

All the best, Andy

**Comment by sy6sy2** [comment]
Hi! fine and you?

Sorry didn't have time to check, is the issue still here?

**Comment by lowflyerUK** [comment]
Hi!

Yes, all fine here thanks :)

telerama.fr has still only got programs until Monday morning around 07:00.
So less than 3 days from now. Maybe that is all they will do now?

All the best, Andy

**Comment by sy6sy2** [comment]
You are right: As we can see here https://television.telerama.fr/tele/grille?jour=+2&heure=11 we have programs for Sunday but not for Monday 😕 

The good news is that it's not a script issue 😛
