### ISSUE TITLE
TNT France files missing

### ISSUE THREAD

**Issue by bouscram** [Catch-up-TV-and-More/xmltv#8]
Hi. I just spotted two problems which seem to be new:
- The tv_guide_fr_local.xml file is in UTC, not local time
- the tv_guide_fr_tnt_local.xml file is missing.

**Comment by sy6sy2** [comment]
Hi!
Concerning TNT, this is because I made some changes recently and I disabled TNT files temporarily ; I will try to add this file again today 😉 
Concerning UTC time I will check that!

Thank you!

**Comment by sy6sy2** [comment]
I just commit something. Can you check that both issues are resolved for you?
Thank you very munch!

**Comment by bouscram** [comment]
It look OK, thanks!
