### ISSUE TITLE
Remove France Ô from french tv guide

### ISSUE THREAD

**Issue by billy34** [Catch-up-TV-and-More/xmltv#9]
Hello
It's maybe time to remove channel 19 (France Ô) from tv_guide_fr as this channel is discontinued.
By the way thank you for this plugin and EPG

**Comment by sy6sy2** [comment]
Hi! Sorry for the delay, I am currently working on improving the TV guide part of catch up tv and more.

> It's maybe time to remove channel 19 (France Ô) from tv_guide_fr as this channel is discontinued.

I just removed France O from the config file.
I will also add CultureBox later.

> By the way thank you for this plugin and EPG

🙏🏻
